name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: Khizanag/iOS-Toolkit/.github/workflows/ios-ci.yml@v1.1.0
    with:
      packages: '["."]'
